builds:
  # add here as well if you ever change this https://github.com/Bloodmallet/bloodytools/blob/master/bloodytools/simulations/talent_tree_paths/priest_shadow.yaml
  yshaarj-da:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEhUQSSSJJSgSakEJSkQEkINpFSCA # DA_yshaarj_yogg_370842075652015_AoE
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIi0IBAAAAAAAAAAAAgIJKRIFSSSSJiEokGJRiEJEBJSTahkAA # DA_yshaarj_yogg_370842360324015_AoE
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIINOQAAAAAAAAAAAAAkIJpEhU0SSkUSIBKpRSkIRCRQi0kWIJAA # DA_yshaarj_cthun_216978847948479_ST
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEhUQSSSJJSgSakEJSkQEkINpFSCA # DA_yshaarj_yogg_370842075652015_AoE
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAIiISAAAAAAAAAAAAAIJiSESBJJJlkIBKpRSkIRCRQi0kWIJAA # DA_yshaarj_yogg_370837790089135_AoE
  yshaarj-yogg-vf:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAIi0IBAAAAAAAAAAAAgkIHoEh0IJJJlgEokGJRiEJEBJSTahkAA # VF_yshaarj_yogg_370910485225391_AoE
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAIi0IBAAAAAAAAAAAAgIJKRINSSSSJiEokGJRiEJEBJSTahkAA # VF_yshaarj_yogg_370842360324015_AoE
    single: BIQAAAAAAAAAAAAAAAAAAAAAAIi0iEAAAAAAAAAAAAAikoEpJNtIRSJhEokGJRiEJEBJSTahkAA # VF_yshaarj_yogg_370843904366271_ST
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAIi0IBAAAAAAAAAAAAgIJKRINSSSSJiEokGJRiEJEBJSTahkAA # VF_yshaarj_yogg_370842360324015_AoE
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAIigEAAAAAAAAAAAAASioEh04AJJJlkIBKpRSkIRCRQi0kWIJAA # VF_yshaarj_yogg_370837806342063_AoE
  cthun-yogg-vf:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAgINSAAAAAAAAAAAAAkDkIpEh0IJJJlgEokGJRiEJEBJSTahkAA # VF_cthun_yogg_444577764286383_AoE
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAgIIBAAAAAAAAAAAAQikkSESjkkkUiDIBKpRSkIRCRQi0kWIJAA # VF_cthun_yogg_445673038651311_AoE
    single: BIQAAAAAAAAAAAAAAAAAAAAAAgINSAAAAAAAAAAAAAkDkIpEh0IJJJlgEokGJRiEJEBJSTahkAA # VF_cthun_yogg_444577764286383_AoE
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAgINSAAAAAAAAAAAAAkDIJpEh04AJJJlISgSakEJSkQEkINpFSCA # VF_cthun_yogg_444578090426287_AoE
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAgIIBAAAAAAAAAAAAQSikSESDJJJlISgSakEJSkQEkINpFSCA # VF_cthun_yogg_445673299713967_AoE
gear:
  head: "draconic_hierophants_archcowl,id=200327,ilevel=424"
  neck: "eye_of_the_vengeful_hurricane,id=195496,ilevel=421"
  shoulders: "draconic_hierophants_wisdom,id=200329,ilevel=424"
  back: "fireproof_drape,id=193763,ilevel=421"
  chest: "draconic_hierophants_vestment,id=200324,ilevel=421"
  wrists: "manawracker_bindings,id=134310,ilevel=421"
  hands: "draconic_hierophants_grips,id=200326,ilevel=421"
  waist: "sky_saddle_cord,id=193691,ilevel=421"
  legs: "leggings_of_swirling_runes,id=133610,ilevel=421" # todo is this even obtainable?
  feet: "sandals_of_the_wild_sovereign,id=195532,ilevel=424"
  finger1: "seal_of_filial_duty,id=195526,ilevel=430"
  finger2: "woebearers_band,id=133638,ilevel=421"
  trinket1: "horn_of_valor,id=133642,ilevel=421"
  trinket2: "furious_ragefeather,id=193677,ilevel=421"
  main_hand: "final_grade,id=193707,ilevel=421"
  off_hand: ""
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character. Lists each consumable at ranks 1, 2, and 3."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only."
    builds: true
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims Food and Augment Rune consumables you can use to augment your character."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot. Lists each enchant at ranks 1, 2, and 3."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - enchants.simc
  gems:
    description: "Sims all available gems against each other. Lists each gem at ranks 1, 2, and 3."
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - gems.simc
  racials:
    description: "Swaps out the racial that includes all stat effects or special abilities where they prove to be a DPS increase."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  special-gear:
    description: "Sims unique gear with effects to see the DPS gain. Includes Tailoring, Jewelcrafting, and Inscription gear, crafted with BiS stats when possible. Compared against Mythic BiS gear from the Raid or Mythic+ gear.<br><br>A negative DPS gain means the crafted piece with BiS stats is worse than the Mythic BiS piece. This usually means the BiS piece has a higher ilvl than the crafted piece."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - gear.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 100 stat each step)."
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims various talent builds generated by Talent Tree Manager. Shows the major cooldown and Idol combination used for that actor, names in gold can be clicked to copy the import string."
    iterations: smart
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - VF-ST.simc
      - VF-AoE.simc
      - DA-ST.simc
      - DA-AoE.simc
  tiersets:
    description: "Sims each tier set currently available by just activating just the set effect, not with the gear."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: Combines the top trinkets together to get your BiS 2 trinkets.
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 350
      - 366
      - 372
      - 376
      - 379
      - 382
      - 385
      - 389
      - 392
      - 395
      - 398
      - 402
      - 405
      - 408
      - 411
      - 415
      - 418
      - 421
      - 424
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for current BiS gear setup..
    builds: true
    weights: true
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsVaultOfTheIncarnates
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
fourTargetWeights: weightsFourTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 10
  retryInterval: 2
analyze:
  markdown: true
  csv: true
  json: true
stats:
  base: 1600
  steps: 700
  total: 10000
  include:
    - mastery
    - haste
    - crit
    - versatility
