builds:
  # add here as well if you ever change this https://github.com/Bloodmallet/bloodytools/blob/master/bloodytools/simulations/talent_tree_paths/priest_shadow.yaml
  yogg-cthun:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAgkQSAAAAAAAAAAAAACKOQkk0iDIJJRkIINSSSkGBJIki0CJBQSA # VF_yogg_cthun_99450837496783_Spike_TS
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAESiQAAAAAAAAAAAAAioIRSSDSSSSkIINSSSkGBJIki0CJBQSA # VF_nzoth_yogg_cthun_136765543790543_Spike_TS
    single: BIQAAAAAAAAAAAAAAAAAAAAAAgkQSAAAAAAAAAAAAACp4ARSSLIJJRkIINSSSkGBJIki0CJBQSA # VF_yogg_cthun_99450833826767_Spike_TS
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAESCSAAAAAAAAAAAAAiDoJRSSLIJJRkIINSSSkGBJIki0CJBQSA # VF_nzoth_yogg_cthun_136765511267279_Spike_DR_TS
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAESISAAAAAAAAAAAAAiDkmEJJNIJJJRig0IJJRaEkgQKSLkEAJA # VF_nzoth_yogg_cthun_136765511538639_Flay_DR_TS
  nzoth-cthun:
    composite: BIQAAAAAAAAAAAAAAAAAAAAAAEkwBOQAAAAAAAAAAAAASiSSkkUCSSSEJCSjkkEpRQCCpItQSAIB # DA_nzoth_cthun_57412802802639_Spike
    dungeons: BIQAAAAAAAAAAAAAAAAAAAAAAEkkEAAAAAAAAAAAAAiDo5ARSSJikEJJJCSjkkEpRQCCpItQSAIB # DA_nzoth_cthun_56327043282895_Spike_DR
    single: BIQAAAAAAAAAAAAAAAAAAAAAAEkwBOQAAAAAAAAAAAAASiSSkkUCSSSEJCSjkkEpRQCCpItQSAIB # DA_nzoth_cthun_57412802802639_Spike
    2t: BIQAAAAAAAAAAAAAAAAAAAAAAEkQSAAAAAAAAAAAAAioJRSSLIJJRkIINSSSkGBJIki0CJBgE # VF_nzoth_cthun_59593606001615_Spike_DR
    4t: BIQAAAAAAAAAAAAAAAAAAAAAAEEJSAAAAAAAAAAAAASOQaJRSSDSSSSkIINSSSkGBJIki0CJBgA # VF_nzoth_cthun_57346197526479_Flay_DR
gear:
  head: "mask_of_the_furnace_seraph,id=202542,ilevel=447" # mastery/haste
  neck: "magmoraxs_fourth_collar,id=204397,ilevel=447" # mastery/haste
  shoulders: "devotion_of_the_furnace_seraph,id=202540,ilevel=450" # haste/crit
  back: "drape_of_the_dracthyr_trials,id=204467,ilevel=447" # haste/vers
  chest: "command_of_the_furnace_seraph,id=202545,ilevel=447" # crit/mastery
  wrists: "sunfrost_wristwraps,id=139130,ilevel=447" # haste/crit
  hands: "grasp_of_the_furnace_seraph,id=202543,ilevel=444" # mastery/haste
  waist: "lost_heros_waist_wrap,id=193816,ilevel=447" # mastery/haste
  legs: "riverrider_legwraps,id=134427,ilevel=447" # mastery/haste
  feet: "treads_of_fractured_realities,id=204392,ilevel=450" # crit/mastery
  finger1: "loop_of_pulsing_veins,id=159463,ilevel=447" # haste/mastery
  finger2: "loop_of_vitriolic_intent,id=134530,ilevel=447" # haste/mastery
  trinket1: "spoils_of_neltharus,id=193773,ilevel=447"
  trinket2: "neltharions_call_to_suffering,id=204211,ilevel=457"
  main_hand: "lavaflow_control_rod,id=202570,ilevel=447" # haste/vers
  off_hand: "echos_maddening_volume,id=204324,ilevel=450" # mastery/haste
sims:
  alchemy:
    description: "Sims alchemy consumables you can use to augment your character. Lists each consumable at ranks 1, 2, and 3."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - alchemy.simc
  apl:
    description: "APL Sims used for testing rotational changes only."
    builds: false
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - apl.simc
  consumables:
    description: "Sims Food and Augment Rune consumables you can use to augment your character."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - consumables.simc
  enchants:
    description: "Sims all possible enchants to your characters gear by slot. Lists each enchant at ranks 1, 2, and 3."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - enchants.simc
  gems:
    description: "Sims all available gems against each other. Lists each gem at ranks 1, 2, and 3."
    iterations: 20000
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - 1
      - 2
      - 3
    files:
      - gems.simc
  racials:
    description: "Swaps out the racial that includes all stat effects or special abilities where they prove to be a DPS increase."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - racials.simc
  special-gear:
    description: "Sims unique gear with effects to see the DPS gain. Includes Tailoring, Jewelcrafting, and Inscription gear, crafted with BiS stats when possible. Compared against Mythic BiS gear from the Raid or Mythic+ gear.<br><br>A negative DPS gain means the crafted piece with BiS stats is worse than the Mythic BiS piece. This usually means the BiS piece has a higher ilvl than the crafted piece."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - gear.simc
  stats:
    description: "Stat distribution sim to see where we would want to add stats given the option. Each letter stands for a secondary stat and the number indicates how many steps were added to that build. So H10 means we add 10 steps of haste (currently 100 stat each step)."
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  talents:
    description: "Sims various talent builds generated by Talent Tree Manager. Shows the major cooldown and Idol combination used for that actor, names in gold can be clicked to copy the import string."
    iterations: smart
    builds: false
    weights: false
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - DA-Spike.simc
      - DA-Flay.simc
      - DA-Spike_DR.simc
      - DA-Flay_DR.simc
      - DA-Spike_TS.simc
      - DA-Flay_TS.simc
      - DA-Spike_DR_TS.simc
      - DA-Flay_DR_TS.simc
      - VF-Spike.simc
      - VF-Flay.simc
      - VF-Spike_DR.simc
      - VF-Flay_DR.simc
      - VF-Spike_TS.simc
      - VF-Flay_TS.simc
      - VF-Spike_DR_TS.simc
      - VF-Flay_DR_TS.simc
  talents-top:
    description: "Shows top talents."
    builds: false
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - talents.simc
  tiersets:
    description: "Sims each tier set currently available by just activating just the set effect, not with the gear."
    builds: true
    weights: false
    chart: true
    lookupType: spell
    steps:
      - DPS
    files:
      - tiersets.simc
  trinket-combos:
    description: Combines the top trinkets together to get your BiS 2 trinkets.
    builds: true
    weights: false
    chart: true
    lookupType: none
    steps:
      - DPS
    files:
      - generated.simc
  trinkets:
    description: "Sims all trinkets by themselves (no second trinket)."
    builds: true
    weights: false
    chart: true
    lookupType: item
    steps:
      - 402
      - 405
      - 408
      - 411
      - 415
      - 418
      - 421
      - 424
      - 428
      - 431
      - 434
      - 437
      - 441
      - 444
      - 447
      - 450
      - 457
    files:
      - raid.simc
      - dungeons.simc
      - other.simc
  weights:
    description: Stat weight sims for current BiS gear setup..
    builds: true
    weights: true
    chart: false
    lookupType: none
    steps:
      - DPS
    files:
      - weights.simc
compositeWeights: weightsAberrusTheShadowedCrucible
singleTargetWeights: weightsSingle
twoTargetWeights: weightsTwoTargets
fourTargetWeights: weightsFourTargets
singleTargetProfiles:
  - pw_na_1
  - lm_na_1
  - hm_na_1
simcBuild: nightly
defaultIterations: 10000
raidbots:
  apiUrlBase: https://www.raidbots.com
  numOfRetries: 100
  retryInterval: 10
analyze:
  markdown: true
  csv: true
  json: true
stats:
  base: 1600
  steps: 1000
  total: 12600
  include:
    - mastery
    - haste
    - crit
    - versatility
